services:
  postgres:
    image: postgres:15
    container_name: postgres_dev
    environment:
      POSTGRES_DB: mscairline_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  your-app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mscairline_dev
      DB_USER: postgres
      DB_PASSWORD: password

volumes:
  postgres_data: